In [5]:
import pandas as pd

In [6]:
data = pd.read_csv("zomato.csv")

In [7]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [8]:
data.tail()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [9]:
'''
Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations
'''

'\nDeleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nRemove the NaN values from the dataset\nCleaning individual columns.\nCheck for some more Transformations\n'

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [11]:
data.shape

(51717, 17)

# 1. Deleting redundant columns.

In [12]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [13]:
columns_to_drop = ['url', 'address','votes', 'phone', 'location', 'rest_type', 'cuisines', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)']
columns_to_keep = ['name', 'online_order', 'book_table', 'rate', 'dish_liked','approx_cost(for two people)']

In [14]:
len(columns_to_drop)

11

In [15]:
len(columns_to_keep)

6

In [16]:
data.shape

(51717, 17)

In [17]:
data = data[columns_to_keep]

In [18]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# 2. Renaming the columns

In [19]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [20]:
data_renamed_columns = []

for i in data.columns:
    data_renamed_columns.append(i.upper())

data_renamed_columns

['NAME',
 'ONLINE_ORDER',
 'BOOK_TABLE',
 'RATE',
 'DISH_LIKED',
 'APPROX_COST(FOR TWO PEOPLE)']

In [21]:
data.columns = data_renamed_columns

In [22]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

# 3. Dropping duplicates

In [23]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [24]:
data.duplicated().sum()

np.int64(32808)

In [25]:
data.drop_duplicates(inplace=True)

In [26]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51631,Just Parathas,No,No,3.4 /5,NaN,250
51632,SeeYa Restaurant,No,No,3.3 /5,NaN,350
51641,Andhra Spices,No,No,3.2 /5,NaN,NaN
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"

In [27]:
data.duplicated().sum()

np.int64(0)

# 4. Remove the NaN values from the dataset

In [28]:
data.isna()

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
51631,False,False,False,False,True,False
51632,False,False,False,False,True,False
51641,False,False,False,False,True,True
51677,False,False,False,False,False,False
51714,False,False,False,True,True,False

In [29]:
data.isna().sum()

NAME                               0
ONLINE_ORDER                       0
BOOK_TABLE                         0
RATE                            2418
DISH_LIKED                     10587
APPROX_COST(FOR TWO PEOPLE)      140
dtype: int64

In [30]:
data.dropna()

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [31]:
data = data.dropna()

In [32]:
data.reset_index(inplace=True)

In [33]:
data

,index,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
8245,51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [34]:
data.drop(columns=['index'],inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_3800\2136747082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns=['index'],inplace=True)

In [35]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

# 5. Cleaning individual columns

In [37]:
type(data["RATE"][3])

str

In [39]:
data['RATE'] = data["RATE"].str.replace(" ","")

C:\Users\Admin\AppData\Local\Temp\ipykernel_3800\3324909636.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['RATE'] = data["RATE"].str.replace(" ","")

In [40]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5/5,Manchow Soup,800
8246,Breakfast House,No,No,3.6/5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8/5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2/5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5/5,"Biryani, Andhra Meal",800

In [42]:
data["RATE"] = data["RATE"].str.replace("/"," out of ")

C:\Users\Admin\AppData\Local\Temp\ipykernel_3800\888144389.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["RATE"] = data["RATE"].str.replace("/"," out of ")

In [43]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,Yes,Yes,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of 5,Masala Dosa,300
4,Grand Village,No,No,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 out of 5,"Biryani, Andhra Meal",800

In [46]:
data["ONLINE_ORDER"].apply(lambda x: 1 if x=="Yes" else 0)

0       1
1       1
2       1
3       0
4       0
       ..
8245    0
8246    0
8247    1
8248    0
8249    0
Name: ONLINE_ORDER, Length: 8250, dtype: int64

In [47]:
data["BOOK_TABLE"].apply(lambda x: 1 if x=="Yes" else 0)

0       1
1       0
2       0
3       0
4       0
       ..
8245    0
8246    0
8247    0
8248    1
8249    0
Name: BOOK_TABLE, Length: 8250, dtype: int64

In [48]:
data['ONLINE_ORDER'] = data["ONLINE_ORDER"].apply(lambda x: 1 if x=="Yes" else 0)
data["BOOK_TABLE"] = data["BOOK_TABLE"].apply(lambda x: 1 if x=="Yes" else 0)

C:\Users\Admin\AppData\Local\Temp\ipykernel_3800\2321590894.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ONLINE_ORDER'] = data["ONLINE_ORDER"].apply(lambda x: 1 if x=="Yes" else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_3800\2321590894.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["BOOK_TABLE"] = data["BOOK_TABLE"].apply(lambda x: 1 if x=="Yes" else 0)

In [49]:
data

,NAME,ONLINE_ORDER,BOOK_TABLE,RATE,DISH_LIKED,APPROX_COST(FOR TWO PEOPLE)
0,Jalsa,1,1,4.1 out of 5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,0,4.1 out of 5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,0,3.8 out of 5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,0,3.7 out of 5,Masala Dosa,300
4,Grand Village,0,0,3.8 out of 5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,0,2.5 out of 5,Manchow Soup,800
8246,Breakfast House,0,0,3.6 out of 5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,0,3.8 out of 5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,1,4.2 out of 5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,0,2.5 out of 5,"Biryani, Andhra Meal",800